### PR TITLE
Fix Map Popup "List Flights" Quote Escaping Issue

### LINKED ISSUE #1220: List flights not working for certain airports
For some reason, for at least a few weeks, I've been unable to list flights for certain airports. For instance, ORD and YYT both do nothing when I try to list flights. The spinning plane doesn't appear, it doesn't give me a blank list, it just doesn't change anything. I'm not sure whether this is a problem with these airports (i.e. do others have the same problem with these airports), or something specific in my list of flights?

I clicked around a whole bunch of different airports that I've flown to today and also found NCE has the same issue. No common factors between these airports or my flights involving them, as far as I can tell.

### PR DESCRIPTION
**Pull request by chrisrosset**
Airports with single quotes in their description (e.g. ORD with its "Chicago O'Hare Internation. (ORD), United States") have their List Flights links broken because of an escaping issue between JS and HTML.

Clicking on the link produces the following error in Firefox:

```
Uncaught SyntaxError: "" string literal contains an unescaped line break
```

The link itself looks like this in HTML:

```txt
<a href="#" onclick="JavaScript:xmlhttpPost(&quot;/php/flights.php&quot;,3830, &quot;Chicago%20O" hare%20international%20airport%20(%3cb%3eord%3c="" b%3e)%3cbr%3e%3csmall%3echicago,%20united%20states%3c="" small%3e%3cbr%3eflights:%203");'=""><img src="/img/icon_copy.png" title="List my flights" width="16" height="16"></a>
```

You can see that the browser stopped parsing the `onclick` quotes right before the quote in "O'Hare". This is because the JS which generated this line of HTML looks like this (slightly abridged):

```js
desc += " <a href='#' onclick='JavaScript:xmlhttpPost(\"" + URL_FLIGHTS + "\"," + apid + ", \"" + encodeURI(airport.attributes.desc) + "\");'>"
```

The single quote right after `onclick` ends up being matched against the quote in the airport description.

Fixes https://github.com/jpatokal/openflights/issues/1220.

### CODE REVIEW

**Comment by chrisrosset** [comment]
I'll be honest, this is not a pretty fix but wanted to get a conversation started with the smallest change possible.

FWIW, it works (as far as I tell). I tested with:
- ORD: **Chicago O'Hare International Airport**
- NCE: **St. John's International Airport**
- YYT: **Nice-Côte d'Azur Airport**
- ZMG: **Magdeburg "City" Airport** to test a description with a double quote

**Comment by Adam-C-Smith** [comment]
> I'll be honest, this is not a pretty fix but wanted to get a conversation started with the smallest change possible.
> 
> FWIW, it works (as far as I tell). I tested with:
> 
> * ORD: **Chicago O'Hare International Airport**
> * NCE: **St. John's International Airport**
> * YYT: **Nice-Côte d'Azur Airport**
> * ZMG: **Magdeburg "City" Airport** to test a description with a double quote

Strange, because I continue to have this issue with ORD, YYT, and NCE...

**Comment by reedy** [comment]
> > I'll be honest, this is not a pretty fix but wanted to get a conversation started with the smallest change possible.
> > FWIW, it works (as far as I tell). I tested with:
> > 
> > * ORD: **Chicago O'Hare International Airport**
> > * NCE: **St. John's International Airport**
> > * YYT: **Nice-Côte d'Azur Airport**
> > * ZMG: **Magdeburg "City" Airport** to test a description with a double quote
> 
> Strange, because I continue to have this issue with ORD, YYT, and NCE...

Yeah, code merged here doesn't mean code deployed, unfortunately. I don't have access to do so.

Chris would be referring to it working in his dev env.

It should be deployed soon.

**Comment by Adam-C-Smith** [comment]
This fix does seem to have been deployed eventually, and has partially sorted the issue. Unfortunately, not entirely. The examples I had cited were YYT, ORD, and NCE. This now works for ORD and NCE, but not YYT. Which is particularly interesting because the single quote was the problem with both ORD and YYT. Is it possible the issue is with the single quote for YYT being in the place name rather than just the airport name?

**Comment by reedy** [comment]
I do see a `Uncaught SyntaxError: "" string literal contains an unescaped line break` when clicking List Routes...

```
<a href="#" onclick="JavaScript:xmlhttpPost(&quot;/php/flights.php&quot;,&quot;R1354,1354&quot;, &quot;Nice-C%C3%B4te%20d" azur%20airport%20(%3cb%3ence%3c="" b%3e)%3cbr%3e%3csmall%3enice,%20france%3cbr%3e135%20routes%3c="" small%3e");'="">
<img src="/img/icon_copy.png" width="16" height="16" title="List all routes from this airport">
</a>
```

Screenshot 2024-01-07 at 15 53 37

I don't think it's because of it being in the place name (the whole name is in the airport name field - `Nice-Côte d'Azur Airport`)

Screenshot 2024-01-07 at 16 00 01

**Pull request merged**
