### PR TITLE
Add LICENSE file

### PR DESCRIPTION
**Pull request by johanricher**
Hi,

The LICENSE file is needed on the repo in order to state clearly the copyright. The [ODbL license](https://openflights.org/data.html#license) is displayed on the website but should also be added here.

Thanks for this project and your work!

### CODE REVIEW

**Comment by jpatokal** [comment]
Otherwise happy to accept, but the encoding looks messed up: the file is full of "â€“?

**Comment by johanricher** [comment]
Sorry, weird encoding problem on my end with [the original file](https://www.opendatacommons.org/files/2018/02/odbl-10.txt).

**Comment by jpatokal** [comment]
New airport edit suggestion submitted by chenqtao:

Array
(
    [apid] => 10321
    [name] => Hangzhou East Railway Station
    [city] => Hangzhou
    [country] => China
    [iata] => 
    [icao] => 
    [x] => 120.208
    [y] => 30.2932
    [elevation] => 40
    [timezone] => 3
    [dst] => U
)
;

Existing, potentially conflicting airport information:

```
Array
(
    [name] => Hangzhou East Railway Station
    [city] => Hangzhou
    [country] => China
    [iata] => 
    [icao] => 
    [x] => 120.208
    [y] => 30.2932
    [elevation] => 40
    [apid] => 10321
    [uid] => 5329
    [timezone] => 8
    [dst] => U
    [tz_id] => 
    [type] => station
    [source] => User
)

```

Cross-check this edit on other sites with compatible licensing:
- OurAirports: http://ourairports.com/airports//pilot-info.html
- Wikipedia: http://www.google.com/search?q=wikipedia%20%20airport&btnI

**Comment by jpatokal** [comment]
Merged, thank you!

**Comment by johanricher** [comment]
Awesome! Keep up the good job.

**Pull request merged**
